var annotated =
[
    [ "tinyxml2", null, [
      [ "Entity", "structtinyxml2_1_1_entity.html", "structtinyxml2_1_1_entity" ],
      [ "StrPair", "classtinyxml2_1_1_str_pair.html", "classtinyxml2_1_1_str_pair" ],
      [ "DynArray", "classtinyxml2_1_1_dyn_array.html", "classtinyxml2_1_1_dyn_array" ],
      [ "MemPool", "classtinyxml2_1_1_mem_pool.html", "classtinyxml2_1_1_mem_pool" ],
      [ "MemPoolT", "classtinyxml2_1_1_mem_pool_t.html", "classtinyxml2_1_1_mem_pool_t" ],
      [ "XMLVisitor", "classtinyxml2_1_1_x_m_l_visitor.html", "classtinyxml2_1_1_x_m_l_visitor" ],
      [ "XMLUtil", "classtinyxml2_1_1_x_m_l_util.html", null ],
      [ "XMLNode", "classtinyxml2_1_1_x_m_l_node.html", "classtinyxml2_1_1_x_m_l_node" ],
      [ "XMLText", "classtinyxml2_1_1_x_m_l_text.html", "classtinyxml2_1_1_x_m_l_text" ],
      [ "XMLComment", "classtinyxml2_1_1_x_m_l_comment.html", "classtinyxml2_1_1_x_m_l_comment" ],
      [ "XMLDeclaration", "classtinyxml2_1_1_x_m_l_declaration.html", "classtinyxml2_1_1_x_m_l_declaration" ],
      [ "XMLUnknown", "classtinyxml2_1_1_x_m_l_unknown.html", "classtinyxml2_1_1_x_m_l_unknown" ],
      [ "XMLAttribute", "classtinyxml2_1_1_x_m_l_attribute.html", "classtinyxml2_1_1_x_m_l_attribute" ],
      [ "XMLElement", "classtinyxml2_1_1_x_m_l_element.html", "classtinyxml2_1_1_x_m_l_element" ],
      [ "XMLDocument", "classtinyxml2_1_1_x_m_l_document.html", "classtinyxml2_1_1_x_m_l_document" ],
      [ "XMLHandle", "classtinyxml2_1_1_x_m_l_handle.html", "classtinyxml2_1_1_x_m_l_handle" ],
      [ "XMLConstHandle", "classtinyxml2_1_1_x_m_l_const_handle.html", "classtinyxml2_1_1_x_m_l_const_handle" ],
      [ "XMLPrinter", "classtinyxml2_1_1_x_m_l_printer.html", "classtinyxml2_1_1_x_m_l_printer" ]
    ] ],
    [ "Breakout", "class_breakout.html", "class_breakout" ],
    [ "DemoMoverSprite", "class_demo_mover_sprite.html", "class_demo_mover_sprite" ],
    [ "MouseDemo", "class_mouse_demo.html", "class_mouse_demo" ],
    [ "PathFindingSprite", "class_path_finding_sprite.html", "class_path_finding_sprite" ],
    [ "QuadTreeDemoScene", "class_quad_tree_demo_scene.html", "class_quad_tree_demo_scene" ],
    [ "SortingModeDemoScene", "class_sorting_mode_demo_scene.html", "class_sorting_mode_demo_scene" ],
    [ "TileEngineScene", "class_tile_engine_scene.html", "class_tile_engine_scene" ],
    [ "XDL_Camera", "class_x_d_l___camera.html", "class_x_d_l___camera" ],
    [ "XDL_Collision", "class_x_d_l___collision.html", "class_x_d_l___collision" ],
    [ "XDL_CollisionManager", "class_x_d_l___collision_manager.html", "class_x_d_l___collision_manager" ],
    [ "XDL_ContentManager", "class_x_d_l___content_manager.html", "class_x_d_l___content_manager" ],
    [ "XDL_Game", "class_x_d_l___game.html", "class_x_d_l___game" ],
    [ "XDL_GameObject", "class_x_d_l___game_object.html", "class_x_d_l___game_object" ],
    [ "XDL_Input", "class_x_d_l___input.html", "class_x_d_l___input" ],
    [ "XDL_Keyboard", "class_x_d_l___keyboard.html", "class_x_d_l___keyboard" ],
    [ "XDL_Layer", "class_x_d_l___layer.html", "class_x_d_l___layer" ],
    [ "XDL_Mouse", "class_x_d_l___mouse.html", "class_x_d_l___mouse" ],
    [ "XDL_PathFinder", "class_x_d_l___path_finder.html", "class_x_d_l___path_finder" ],
    [ "XDL_QuadTree", "class_x_d_l___quad_tree.html", "class_x_d_l___quad_tree" ],
    [ "XDL_Scene", "class_x_d_l___scene.html", "class_x_d_l___scene" ],
    [ "XDL_SceneManager", "class_x_d_l___scene_manager.html", "class_x_d_l___scene_manager" ],
    [ "XDL_Sprite", "class_x_d_l___sprite.html", "class_x_d_l___sprite" ],
    [ "XDL_SpriteBatch", "class_x_d_l___sprite_batch.html", "class_x_d_l___sprite_batch" ],
    [ "XDL_TestScene", "class_x_d_l___test_scene.html", "class_x_d_l___test_scene" ],
    [ "XDL_Tile", "class_x_d_l___tile.html", "class_x_d_l___tile" ],
    [ "XDL_TileEngine", "class_x_d_l___tile_engine.html", "class_x_d_l___tile_engine" ]
];